### ISSUE TITLE
"Thanks for flagging"

### ISSUE THREAD

**Issue by kingboyk** [SOBotics/QueenReporter#3]
Could Queen Reporter hide the "Thanks for flagging" message which SO have recently added?

**Comment by geisterfurz007** [comment]
Notes:
 - Gotta add a new checkbox to the flagging dialog (maybe someone actually likes the dialog; who am I to judge).
 - Gotta get faster seeing the selector for the

**Comment by mvarendorff** [comment]
Closed with a75581a5ecd1abc52c605909768f5ab1cc1917cf

**Comment by mvarendorff** [comment]
Against expectations this seems to remove the popup before it is made visible. I hope this is what you meant :)
