### ISSUE TITLE
Flag dialog, two or...six checkboxes?

### ISSUE THREAD

**Issue by GolfingSuccess** [SOBotics/QueenReporter#5]
When you attempt to open the comment flag dialog twice in a row too quickly, you get this error:

> You may only attempt to flag this comment every 3 seconds.

After the 3 seconds pass, if this error was shown before, this happens:

![untitled](https://user-images.githubusercontent.com/19519588/46905861-52276d80-cf02-11e8-9059-6763b02a8cfa.png)

Google Chrome 69.0.3497.100, Tampermonkey 4.7, Queen Reporter 0.9.

**Comment by mvarendorff** [comment]
Oh boy that one gives me BEEEEEEEES-flashbacks. I will look into it, thanks for reporting!
