### ISSUE TITLE
Send NC as feedback when flagging a comment as NLN

### ISSUE THREAD

**Issue by Filnor** [SOBotics/QueenReporter#6]
Currently, when we flag a comment with auto feedback enabled, `fp` is sent. That gives the look that we're telling Queen "Nah, that comment is fine" but actually it's borderline rude. Feeding back `nc` instead would fit perfectly IMO. [Other users share this opinion](https://chat.stackoverflow.com/transcript/message/44268658#44268658).

**Comment by mvarendorff** [comment]
https://chat.stackoverflow.com/transcript/message/44268861#44268861
Idea suggested:
Add a new flagging option in the dialog that flags NLN but feeds back nc
Background: https://chat.stackoverflow.com/transcript/message/44268881#44268881
