### ISSUE TITLE
Getting assignment to undeclared variable GM

### ISSUE THREAD

**Issue by dippas** [SOBotics/QueenReporter#9]
In the console is showing this error:

`ReferenceError:  assignment to undeclared variable GM Line 26, column 3: GM = {}; ^`

**Comment by adeak** [comment]
What browser and version are you using?

**Comment by dippas** [comment]
Firefox 67.0.4 (64-bit)

**Comment by adeak** [comment]
I don't speak any JS but the error seems clear enough, there really is an [undeclared assignment to `GM` here](https://github.com/SOBotics/QueenReporter/blob/master/QueenReporter.user.js#L25-L27). [This](https://stackoverflow.com/questions/22850380/assignment-to-undeclared-variable-when-using-for-i-0) suggests that this is only a problem in strict mode; I wonder whether strict mode depends on the browser or personal preferences and how. Anyway it's probably easy to fix with the right declaration of `GM`.

**Comment by dippas** [comment]
Ya it seem like that, I really didn't test it , I happened to have the console opened and it showed that error,therefore I thought it was a good idea to open an issue

**Comment by mvarendorff** [comment]
Hey there o/
What userscript addon are you using?

**Comment by dippas** [comment]
@geisterfurz007  using violentmonkey

**Comment by mvarendorff** [comment]
I am simply assuming that that is the issue. I will look into this when I have time. Another quick question: Is this something that can always be reproduced or is it something that only happens sometimes.

I think defining the GM variable in a wider scope should fix the issue; I am not sure if the userscript still works on ViolentMonkey though. We'll see.

**Comment by dippas** [comment]
In my work PC it was happening all the time. In my home PC (which has the same setup) I can't reproduce the error

**Comment by mvarendorff** [comment]
I pushed a change. I simply added var to the statement. I am not tooooo happy with using var but that was the fastest fix I could think of. Would be great if you could update and see if the issue still exists :)

I will look into a nicer fix when I have time.

**Comment by dippas** [comment]
@geisterfurz007 sorry for the delay. all is good. closing the issue

**Comment by mvarendorff** [comment]
Hey @dippas, would be great, if you could test another potential fix for me. The one that is put in place currently, unfortunately seems to break QR in its entirety for me and likely others, so having the `var` in there is not a good thing to have.

Could you replace that line with `window.GM = {};` and see if it still works on that magic machine with the issue you reported originally?

**Comment by dippas** [comment]
@geisterfurz007  yes I can tomorrow I'll try to reproduce this and get back to you asap.

**Comment by dippas** [comment]
@geisterfurz007  seems fine to me :)

**Comment by mvarendorff** [comment]
Thanks for the feedback :heart:
